name: FlightBal
version: '${project.version}'
main: com.savage.flightbal.FlightBal
api-version: 1.19
commands:
  showbal:
    description: shows a player's balence
    permission: flightsmp.showbal
    aliases: cbal