#A big thank you to loving11ish for helping me with debugging, and also creating the plugin that this is based on!



#=======================================================================#
#__________.__                              .____    .__          __    #
#\______   \  | _____  ___.__. ___________  |    |   |__| _______/  |_  #
#|     ___/  | \__  \<   |  |/ __ \_  __ \ |    |   |  |/  ___/\   __\  #
#|    |   |  |__/ __ \\___  \  ___/|  | \/ |    |___|  |\___ \  |  |    #
#|____|   |____(____  / ____|\___  >__|    |_______ \__/____  > |__|    #
#\/\/         \/                \/       \/                             #
#=======================================================================#

playerlist-name: §x§f§1§2§c§f§b§lP§x§d§b§3§8§f§b§ll§x§c§6§4§3§f§b§la§x§b§0§4§f§f§c§ly§x§9§b§5§a§f§c§le§x§8§5§6§6§f§c§lr§x§7§0§7§1§f§c§ll§x§5§a§7§d§f§d§li§x§4§5§8§8§f§d§ls§x§2§f§9§4§f§d§lt



#===================================================#
#  __________                _____.__.__            #
#  \______   \_______  _____/ ____\__|  |   ____    #
#  |     ___/\_  __ \/  _ \   __\|  |  | _/ __ \    #
#  |    |     |  | \(  <_> )  |  |  |  |_\  ___/    #
#  |____|     |__|   \____/|__|  |__|____/\___  >   #
#===================================================#



profile-name: §x§f§1§2§c§f§b§lP§x§d§1§3§d§f§b§lr§x§b§0§4§f§f§c§lo§x§9§0§6§0§f§c§lf§x§7§0§7§1§f§c§li§x§4§f§8§3§f§d§ll§x§2§f§9§4§f§d§le

#In increments of 9 only!!!
profile-size: 27

